edit_uri: ''
markdown_extensions:
- admonition
- pymdownx.details
- codehilite: {guess_lang: false}
- toc: {permalink: true}
pages:
- Home:
  - {'Why xRally?': index.md}
  - {Quick Start: quick_start.md}
  - {Components: components.md}
  - {Export Results: export.md}
  - {Install Options: install.md}
  - {DB & Upgrades: upgrades.md}
  - {Community: community.md}
  - {License: license.md}
- Use Cases:
  - {Overview: case/index.md}
  - {xRally & Jenkins: case/jenkins.md}
  - {xRally & Travis: case/travis.md}
  - {xRally & CircleCI: case/circleci.md}
  - {'xRally, Elastic & Grafana': case/elastic_grafana.md}
- Architecture:
  - {High Level: arch/index.md}
  - {Glossary: arch/glossary.md}
  - {Plugins Mechanism: arch/plugins.md}
  - {Mastering Env: arch/env.md}
  - {Mastering Task: arch/task.md}
  - {Mastering Verify: arch/verify.md}
- API Reference:
  - {CLI Reference: ref/cli.md}
- Plugins:
  - In-tree:
    - {Plugins: plugins/in_tree/plugins.md}
    - {Config Options: plugins/in_tree/options.md}
  - Docker:
    - {Overview: plugins/docker/overview.md}
    - {Plugins: plugins/docker/plugins.md}
    - {ChangeLog: plugins/docker/changelog.md}
    - {Config Options: plugins/docker/options.md}
  - Kubernetes:
    - {Overview: plugins/kubernetes/overview.md}
    - {Plugins: plugins/kubernetes/plugins.md}
    - {ChangeLog: plugins/kubernetes/changelog.md}
    - {Config Options: plugins/kubernetes/options.md}
  - OpenStack:
    - {Overview: plugins/openstack/overview.md}
    - {Plugins: plugins/openstack/plugins.md}
    - {ChangeLog: plugins/openstack/changelog.md}
    - {Config Options: plugins/openstack/options.md}
repo_name: xrally/xrally
repo_url: https://github.com/xrally/xrally
site_author: xRally team
site_description: Official xRally Documentation
site_name: xRally Docs
site_url: https://xrally.org
theme:
  feature: {tabs: true}
  name: material
